{{- $root := . -}}
{{- range $serviceName, $serviceConfig := .Values.frontend }}
{{- if $serviceConfig.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "metapharm-connect.fullname" $root }}-frontend-{{ $serviceConfig.name }}
  labels:
    {{- include "metapharm-connect.serviceLabels" (dict "root" $root "serviceName" (printf "frontend-%s" $serviceConfig.name)) | nindent 4 }}
spec:
  type: {{ $serviceConfig.type | default "ClusterIP" }}
  ports:
    - port: {{ $serviceConfig.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "metapharm-connect.serviceSelectorLabels" (dict "root" $root "serviceName" (printf "frontend-%s" $serviceConfig.name)) | nindent 4 }}
{{- end }}
{{- end }}
