{{- if .Values.rbac.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.grafana.name }}-admin
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.grafana.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
data:
  {{ .Values.grafana.admin.userKey }}: "{{ .Values.grafana.admin.user }}"
  {{ .Values.grafana.admin.passwordKey }}: "{{ .Values.grafana.admin.password }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.grafana.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{ .Values.grafana.admin.userKey }}: {{ .Values.grafana.admin.user | b64enc }}
  {{ .Values.grafana.admin.passwordKey }}: {{ .Values.grafana.admin.password | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-security
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.grafana.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
type: Opaque
data:
  secret-key: {{ randAlphaNum 32 | b64enc }}

{{- end }}
