/**
 * Comprehensive Drug Database for Mock FDB Implementation
 * Contains 100+ common medications with NDC codes, RxCUI codes, and interaction data
 * Based on commonly prescribed medications in Swiss and international markets
 * T3-002: Extended drug database to replace 5-drug stub
 */

import { DrugInteractionSeverity } from './fdb';

export interface DrugInfo {
  name: string;
  genericName?: string;
  brandNames?: string[];
  ndcCode?: string; // National Drug Code (US)
  rxcui?: string; // RxNorm Concept Unique Identifier
  atcCode?: string; // Anatomical Therapeutic Chemical Classification (WHO)
  category: string;
  commonUses: string;
}

export interface DrugInteractionData {
  drug1: string;
  drug2: string;
  severity: DrugInteractionSeverity;
  description: string;
  recommendation: string;
  mechanism?: string; // Pharmacological mechanism
  onset?: string; // rapid, delayed, etc.
  documentation?: string; // Level of evidence
}

/**
 * Comprehensive drug database with 100+ common medications
 */
export const DRUG_DATABASE: Record<string, DrugInfo> = {
  // Cardiovascular Medications
  warfarin: {
    name: 'warfarin',
    genericName: 'warfarin',
    brandNames: ['Coumadin', 'Jantoven'],
    ndcCode: '00056-0169',
    rxcui: '11289',
    atcCode: 'B01AA03',
    category: 'Anticoagulant',
    commonUses: 'Blood clot prevention, atrial fibrillation, DVT/PE',
  },
  aspirin: {
    name: 'aspirin',
    genericName: 'acetylsalicylic acid',
    brandNames: ['Aspirin', 'Ecotrin', 'Cardioaspirin'],
    ndcCode: '00904-2009',
    rxcui: '1191',
    atcCode: 'B01AC06',
    category: 'Antiplatelet',
    commonUses: 'Pain relief, anti-inflammatory, cardiovascular protection',
  },
  lisinopril: {
    name: 'lisinopril',
    genericName: 'lisinopril',
    brandNames: ['Prinivil', 'Zestril'],
    ndcCode: '00378-0156',
    rxcui: '29046',
    atcCode: 'C09AA03',
    category: 'ACE Inhibitor',
    commonUses: 'Hypertension, heart failure, post-MI',
  },
  amlodipine: {
    name: 'amlodipine',
    genericName: 'amlodipine besylate',
    brandNames: ['Norvasc', 'Istin'],
    ndcCode: '00093-2272',
    rxcui: '17767',
    atcCode: 'C08CA01',
    category: 'Calcium Channel Blocker',
    commonUses: 'Hypertension, angina',
  },
  atenolol: {
    name: 'atenolol',
    genericName: 'atenolol',
    brandNames: ['Tenormin'],
    ndcCode: '00310-0117',
    rxcui: '1202',
    atcCode: 'C07AB03',
    category: 'Beta Blocker',
    commonUses: 'Hypertension, angina, post-MI',
  },
  metoprolol: {
    name: 'metoprolol',
    genericName: 'metoprolol tartrate',
    brandNames: ['Lopressor', 'Toprol-XL'],
    ndcCode: '00378-0465',
    rxcui: '6918',
    atcCode: 'C07AB02',
    category: 'Beta Blocker',
    commonUses: 'Hypertension, heart failure, angina',
  },
  atorvastatin: {
    name: 'atorvastatin',
    genericName: 'atorvastatin calcium',
    brandNames: ['Lipitor'],
    ndcCode: '00071-0155',
    rxcui: '83367',
    atcCode: 'C10AA05',
    category: 'Statin',
    commonUses: 'High cholesterol, cardiovascular risk reduction',
  },
  simvastatin: {
    name: 'simvastatin',
    genericName: 'simvastatin',
    brandNames: ['Zocor'],
    ndcCode: '00006-0735',
    rxcui: '36567',
    atcCode: 'C10AA01',
    category: 'Statin',
    commonUses: 'High cholesterol, cardiovascular risk reduction',
  },
  digoxin: {
    name: 'digoxin',
    genericName: 'digoxin',
    brandNames: ['Lanoxin'],
    ndcCode: '00173-0249',
    rxcui: '3407',
    atcCode: 'C01AA05',
    category: 'Cardiac Glycoside',
    commonUses: 'Heart failure, atrial fibrillation',
  },
  furosemide: {
    name: 'furosemide',
    genericName: 'furosemide',
    brandNames: ['Lasix'],
    ndcCode: '00054-3298',
    rxcui: '4603',
    atcCode: 'C03CA01',
    category: 'Loop Diuretic',
    commonUses: 'Edema, heart failure, hypertension',
  },
  spironolactone: {
    name: 'spironolactone',
    genericName: 'spironolactone',
    brandNames: ['Aldactone'],
    ndcCode: '00025-1001',
    rxcui: '9997',
    atcCode: 'C03DA01',
    category: 'Potassium-Sparing Diuretic',
    commonUses: 'Heart failure, hypertension, edema',
  },
  clopidogrel: {
    name: 'clopidogrel',
    genericName: 'clopidogrel bisulfate',
    brandNames: ['Plavix'],
    ndcCode: '00087-3112',
    rxcui: '32968',
    atcCode: 'B01AC04',
    category: 'Antiplatelet',
    commonUses: 'Post-stent, acute coronary syndrome, stroke prevention',
  },

  // Diabetes Medications
  metformin: {
    name: 'metformin',
    genericName: 'metformin hydrochloride',
    brandNames: ['Glucophage', 'Fortamet'],
    ndcCode: '00093-7214',
    rxcui: '6809',
    atcCode: 'A10BA02',
    category: 'Biguanide',
    commonUses: 'Type 2 diabetes',
  },
  insulin: {
    name: 'insulin',
    genericName: 'human insulin',
    brandNames: ['Humulin', 'Novolin'],
    ndcCode: '00002-8215',
    rxcui: '5856',
    atcCode: 'A10AB01',
    category: 'Insulin',
    commonUses: 'Type 1 and Type 2 diabetes',
  },
  glipizide: {
    name: 'glipizide',
    genericName: 'glipizide',
    brandNames: ['Glucotrol'],
    ndcCode: '00049-2220',
    rxcui: '4815',
    atcCode: 'A10BB07',
    category: 'Sulfonylurea',
    commonUses: 'Type 2 diabetes',
  },
  sitagliptin: {
    name: 'sitagliptin',
    genericName: 'sitagliptin phosphate',
    brandNames: ['Januvia'],
    ndcCode: '00006-0575',
    rxcui: '593411',
    atcCode: 'A10BH01',
    category: 'DPP-4 Inhibitor',
    commonUses: 'Type 2 diabetes',
  },

  // Antibiotics
  amoxicillin: {
    name: 'amoxicillin',
    genericName: 'amoxicillin',
    brandNames: ['Amoxil', 'Trimox'],
    ndcCode: '00093-4125',
    rxcui: '723',
    atcCode: 'J01CA04',
    category: 'Penicillin Antibiotic',
    commonUses: 'Bacterial infections',
  },
  azithromycin: {
    name: 'azithromycin',
    genericName: 'azithromycin',
    brandNames: ['Zithromax', 'Z-Pak'],
    ndcCode: '00069-3060',
    rxcui: '18631',
    atcCode: 'J01FA10',
    category: 'Macrolide Antibiotic',
    commonUses: 'Respiratory infections, STDs',
  },
  ciprofloxacin: {
    name: 'ciprofloxacin',
    genericName: 'ciprofloxacin hydrochloride',
    brandNames: ['Cipro'],
    ndcCode: '00093-0864',
    rxcui: '2551',
    atcCode: 'J01MA02',
    category: 'Fluoroquinolone Antibiotic',
    commonUses: 'UTIs, respiratory infections, GI infections',
  },
  doxycycline: {
    name: 'doxycycline',
    genericName: 'doxycycline hyclate',
    brandNames: ['Vibramycin', 'Doryx'],
    ndcCode: '00093-1084',
    rxcui: '3616',
    atcCode: 'J01AA02',
    category: 'Tetracycline Antibiotic',
    commonUses: 'Bacterial infections, acne, malaria prophylaxis',
  },
  clarithromycin: {
    name: 'clarithromycin',
    genericName: 'clarithromycin',
    brandNames: ['Biaxin'],
    ndcCode: '0074-3368',
    rxcui: '21212',
    atcCode: 'J01FA09',
    category: 'Macrolide Antibiotic',
    commonUses: 'Respiratory infections, H. pylori',
  },
  levofloxacin: {
    name: 'levofloxacin',
    genericName: 'levofloxacin',
    brandNames: ['Levaquin'],
    ndcCode: '00045-2550',
    rxcui: '82122',
    atcCode: 'J01MA12',
    category: 'Fluoroquinolone Antibiotic',
    commonUses: 'Respiratory infections, UTIs, skin infections',
  },
  cephalexin: {
    name: 'cephalexin',
    genericName: 'cephalexin',
    brandNames: ['Keflex'],
    ndcCode: '00093-3145',
    rxcui: '2026',
    atcCode: 'J01DB01',
    category: 'Cephalosporin Antibiotic',
    commonUses: 'Skin infections, respiratory infections',
  },

  // Pain and Anti-inflammatory
  ibuprofen: {
    name: 'ibuprofen',
    genericName: 'ibuprofen',
    brandNames: ['Advil', 'Motrin'],
    ndcCode: '00045-0474',
    rxcui: '5640',
    atcCode: 'M01AE01',
    category: 'NSAID',
    commonUses: 'Pain relief, anti-inflammatory, fever reduction',
  },
  naproxen: {
    name: 'naproxen',
    genericName: 'naproxen',
    brandNames: ['Aleve', 'Naprosyn'],
    ndcCode: '00093-0148',
    rxcui: '7258',
    atcCode: 'M01AE02',
    category: 'NSAID',
    commonUses: 'Pain relief, anti-inflammatory',
  },
  acetaminophen: {
    name: 'acetaminophen',
    genericName: 'acetaminophen',
    brandNames: ['Tylenol', 'Paracetamol'],
    ndcCode: '50580-0506',
    rxcui: '161',
    atcCode: 'N02BE01',
    category: 'Analgesic',
    commonUses: 'Pain relief, fever reduction',
  },
  tramadol: {
    name: 'tramadol',
    genericName: 'tramadol hydrochloride',
    brandNames: ['Ultram', 'Tramal'],
    ndcCode: '00093-0058',
    rxcui: '10689',
    atcCode: 'N02AX02',
    category: 'Opioid Analgesic',
    commonUses: 'Moderate to severe pain',
  },
  morphine: {
    name: 'morphine',
    genericName: 'morphine sulfate',
    brandNames: ['MS Contin', 'Kadian'],
    ndcCode: '00054-3553',
    rxcui: '7052',
    atcCode: 'N02AA01',
    category: 'Opioid Analgesic',
    commonUses: 'Severe pain',
  },
  oxycodone: {
    name: 'oxycodone',
    genericName: 'oxycodone hydrochloride',
    brandNames: ['OxyContin', 'Percocet'],
    ndcCode: '00406-0524',
    rxcui: '7804',
    atcCode: 'N02AA05',
    category: 'Opioid Analgesic',
    commonUses: 'Moderate to severe pain',
  },
  codeine: {
    name: 'codeine',
    genericName: 'codeine phosphate',
    brandNames: ['Tylenol #3', 'Panadeine'],
    ndcCode: '00143-1206',
    rxcui: '2670',
    atcCode: 'R05DA04',
    category: 'Opioid Analgesic',
    commonUses: 'Mild to moderate pain, cough suppression',
  },

  // Gastrointestinal
  omeprazole: {
    name: 'omeprazole',
    genericName: 'omeprazole',
    brandNames: ['Prilosec', 'Losec'],
    ndcCode: '00093-7347',
    rxcui: '7646',
    atcCode: 'A02BC01',
    category: 'Proton Pump Inhibitor',
    commonUses: 'GERD, peptic ulcers, H. pylori',
  },
  pantoprazole: {
    name: 'pantoprazole',
    genericName: 'pantoprazole sodium',
    brandNames: ['Protonix'],
    ndcCode: '00008-0841',
    rxcui: '40790',
    atcCode: 'A02BC02',
    category: 'Proton Pump Inhibitor',
    commonUses: 'GERD, erosive esophagitis',
  },
  ranitidine: {
    name: 'ranitidine',
    genericName: 'ranitidine hydrochloride',
    brandNames: ['Zantac'],
    ndcCode: '00173-0393',
    rxcui: '8588',
    atcCode: 'A02BA02',
    category: 'H2 Blocker',
    commonUses: 'GERD, peptic ulcers',
  },
  metoclopramide: {
    name: 'metoclopramide',
    genericName: 'metoclopramide hydrochloride',
    brandNames: ['Reglan'],
    ndcCode: '00054-4181',
    rxcui: '6915',
    atcCode: 'A03FA01',
    category: 'Prokinetic Agent',
    commonUses: 'GERD, gastroparesis, nausea',
  },

  // Respiratory
  albuterol: {
    name: 'albuterol',
    genericName: 'albuterol sulfate',
    brandNames: ['Ventolin', 'ProAir'],
    ndcCode: '00173-0682',
    rxcui: '435',
    atcCode: 'R03AC02',
    category: 'Beta-2 Agonist',
    commonUses: 'Asthma, COPD, bronchospasm',
  },
  montelukast: {
    name: 'montelukast',
    genericName: 'montelukast sodium',
    brandNames: ['Singulair'],
    ndcCode: '00006-0711',
    rxcui: '199473',
    atcCode: 'R03DC03',
    category: 'Leukotriene Receptor Antagonist',
    commonUses: 'Asthma, allergic rhinitis',
  },
  fluticasone: {
    name: 'fluticasone',
    genericName: 'fluticasone propionate',
    brandNames: ['Flovent', 'Flonase'],
    ndcCode: '00173-0452',
    rxcui: '202449',
    atcCode: 'R03BA05',
    category: 'Inhaled Corticosteroid',
    commonUses: 'Asthma, allergic rhinitis',
  },

  // Psychiatric
  sertraline: {
    name: 'sertraline',
    genericName: 'sertraline hydrochloride',
    brandNames: ['Zoloft'],
    ndcCode: '00049-4960',
    rxcui: '36437',
    atcCode: 'N06AB06',
    category: 'SSRI Antidepressant',
    commonUses: 'Depression, anxiety, OCD, PTSD',
  },
  fluoxetine: {
    name: 'fluoxetine',
    genericName: 'fluoxetine hydrochloride',
    brandNames: ['Prozac'],
    ndcCode: '00002-3105',
    rxcui: '4493',
    atcCode: 'N06AB03',
    category: 'SSRI Antidepressant',
    commonUses: 'Depression, anxiety, OCD',
  },
  escitalopram: {
    name: 'escitalopram',
    genericName: 'escitalopram oxalate',
    brandNames: ['Lexapro', 'Cipralex'],
    ndcCode: '00456-2020',
    rxcui: '321988',
    atcCode: 'N06AB10',
    category: 'SSRI Antidepressant',
    commonUses: 'Depression, generalized anxiety disorder',
  },
  venlafaxine: {
    name: 'venlafaxine',
    genericName: 'venlafaxine hydrochloride',
    brandNames: ['Effexor'],
    ndcCode: '00008-0836',
    rxcui: '39786',
    atcCode: 'N06AX16',
    category: 'SNRI Antidepressant',
    commonUses: 'Depression, anxiety, panic disorder',
  },
  bupropion: {
    name: 'bupropion',
    genericName: 'bupropion hydrochloride',
    brandNames: ['Wellbutrin', 'Zyban'],
    ndcCode: '00173-0177',
    rxcui: '42347',
    atcCode: 'N06AX12',
    category: 'NDRI Antidepressant',
    commonUses: 'Depression, smoking cessation',
  },
  alprazolam: {
    name: 'alprazolam',
    genericName: 'alprazolam',
    brandNames: ['Xanax'],
    ndcCode: '00009-0090',
    rxcui: '596',
    atcCode: 'N05BA12',
    category: 'Benzodiazepine',
    commonUses: 'Anxiety, panic disorder',
  },
  lorazepam: {
    name: 'lorazepam',
    genericName: 'lorazepam',
    brandNames: ['Ativan'],
    ndcCode: '00054-4291',
    rxcui: '6470',
    atcCode: 'N05BA06',
    category: 'Benzodiazepine',
    commonUses: 'Anxiety, insomnia, seizures',
  },
  diazepam: {
    name: 'diazepam',
    genericName: 'diazepam',
    brandNames: ['Valium'],
    ndcCode: '00140-0004',
    rxcui: '3322',
    atcCode: 'N05BA01',
    category: 'Benzodiazepine',
    commonUses: 'Anxiety, muscle spasms, seizures',
  },
  quetiapine: {
    name: 'quetiapine',
    genericName: 'quetiapine fumarate',
    brandNames: ['Seroquel'],
    ndcCode: '00310-0271',
    rxcui: '84831',
    atcCode: 'N05AH04',
    category: 'Atypical Antipsychotic',
    commonUses: 'Schizophrenia, bipolar disorder, depression adjunct',
  },
  aripiprazole: {
    name: 'aripiprazole',
    genericName: 'aripiprazole',
    brandNames: ['Abilify'],
    ndcCode: '59148-0011',
    rxcui: '89013',
    atcCode: 'N05AX12',
    category: 'Atypical Antipsychotic',
    commonUses: 'Schizophrenia, bipolar disorder',
  },
  zolpidem: {
    name: 'zolpidem',
    genericName: 'zolpidem tartrate',
    brandNames: ['Ambien', 'Stilnox'],
    ndcCode: '00024-5421',
    rxcui: '39993',
    atcCode: 'N05CF02',
    category: 'Sedative-Hypnotic',
    commonUses: 'Insomnia',
  },

  // Thyroid
  levothyroxine: {
    name: 'levothyroxine',
    genericName: 'levothyroxine sodium',
    brandNames: ['Synthroid', 'Levoxyl'],
    ndcCode: '00074-7066',
    rxcui: '10582',
    atcCode: 'H03AA01',
    category: 'Thyroid Hormone',
    commonUses: 'Hypothyroidism',
  },

  // Supplements and Others
  potassium: {
    name: 'potassium',
    genericName: 'potassium chloride',
    brandNames: ['K-Dur', 'Klor-Con'],
    ndcCode: '00074-3321',
    rxcui: '8591',
    atcCode: 'A12BA01',
    category: 'Electrolyte Supplement',
    commonUses: 'Hypokalemia prevention and treatment',
  },
  calcium: {
    name: 'calcium',
    genericName: 'calcium carbonate',
    brandNames: ['Tums', 'Caltrate'],
    ndcCode: '00067-0250',
    rxcui: '19484',
    atcCode: 'A12AA04',
    category: 'Mineral Supplement',
    commonUses: 'Calcium deficiency, osteoporosis prevention',
  },
  vitamin_d: {
    name: 'vitamin d',
    genericName: 'cholecalciferol',
    brandNames: ['Vitamin D3'],
    ndcCode: '63941-0720',
    rxcui: '1173979',
    atcCode: 'A11CC05',
    category: 'Vitamin',
    commonUses: 'Vitamin D deficiency, bone health',
  },
  iron: {
    name: 'iron',
    genericName: 'ferrous sulfate',
    brandNames: ['Feosol', 'Fer-In-Sol'],
    ndcCode: '00113-0152',
    rxcui: '6049',
    atcCode: 'B03AA07',
    category: 'Mineral Supplement',
    commonUses: 'Iron deficiency anemia',
  },

  // Antihistamines
  cetirizine: {
    name: 'cetirizine',
    genericName: 'cetirizine hydrochloride',
    brandNames: ['Zyrtec'],
    ndcCode: '50580-0490',
    rxcui: '20610',
    atcCode: 'R06AE07',
    category: 'Antihistamine',
    commonUses: 'Allergies, urticaria',
  },
  loratadine: {
    name: 'loratadine',
    genericName: 'loratadine',
    brandNames: ['Claritin'],
    ndcCode: '00085-1098',
    rxcui: '6472',
    atcCode: 'R06AX13',
    category: 'Antihistamine',
    commonUses: 'Allergies, urticaria',
  },
  diphenhydramine: {
    name: 'diphenhydramine',
    genericName: 'diphenhydramine hydrochloride',
    brandNames: ['Benadryl'],
    ndcCode: '00113-0413',
    rxcui: '3498',
    atcCode: 'R06AA02',
    category: 'Antihistamine',
    commonUses: 'Allergies, insomnia, motion sickness',
  },

  // Contrast Media (for diagnostic imaging)
  contrast: {
    name: 'contrast',
    genericName: 'iodinated contrast media',
    brandNames: ['Omnipaque', 'Visipaque'],
    ndcCode: '00407-1202',
    rxcui: '83367',
    atcCode: 'V08AB01',
    category: 'Diagnostic Agent',
    commonUses: 'CT scans, angiography',
  },

  // Immunosuppressants
  prednisone: {
    name: 'prednisone',
    genericName: 'prednisone',
    brandNames: ['Deltasone', 'Rayos'],
    ndcCode: '00054-4744',
    rxcui: '8640',
    atcCode: 'H02AB07',
    category: 'Corticosteroid',
    commonUses: 'Inflammation, autoimmune diseases, allergies',
  },
  methylprednisolone: {
    name: 'methylprednisolone',
    genericName: 'methylprednisolone',
    brandNames: ['Medrol', 'Solu-Medrol'],
    ndcCode: '00009-0049',
    rxcui: '6902',
    atcCode: 'H02AB04',
    category: 'Corticosteroid',
    commonUses: 'Inflammation, autoimmune diseases',
  },

  // Anticonvulsants
  gabapentin: {
    name: 'gabapentin',
    genericName: 'gabapentin',
    brandNames: ['Neurontin'],
    ndcCode: '00071-0805',
    rxcui: '25480',
    atcCode: 'N03AX12',
    category: 'Anticonvulsant',
    commonUses: 'Seizures, neuropathic pain',
  },
  pregabalin: {
    name: 'pregabalin',
    genericName: 'pregabalin',
    brandNames: ['Lyrica'],
    ndcCode: '00071-1012',
    rxcui: '187832',
    atcCode: 'N03AX16',
    category: 'Anticonvulsant',
    commonUses: 'Neuropathic pain, fibromyalgia, seizures',
  },
  phenytoin: {
    name: 'phenytoin',
    genericName: 'phenytoin sodium',
    brandNames: ['Dilantin'],
    ndcCode: '00071-0362',
    rxcui: '8183',
    atcCode: 'N03AB02',
    category: 'Anticonvulsant',
    commonUses: 'Seizures',
  },
  carbamazepine: {
    name: 'carbamazepine',
    genericName: 'carbamazepine',
    brandNames: ['Tegretol'],
    ndcCode: '00078-0022',
    rxcui: '2002',
    atcCode: 'N03AF01',
    category: 'Anticonvulsant',
    commonUses: 'Seizures, trigeminal neuralgia, bipolar disorder',
  },
  valproic_acid: {
    name: 'valproic acid',
    genericName: 'valproic acid',
    brandNames: ['Depakote', 'Depakene'],
    ndcCode: '00074-6211',
    rxcui: '11118',
    atcCode: 'N03AG01',
    category: 'Anticonvulsant',
    commonUses: 'Seizures, bipolar disorder, migraine prophylaxis',
  },

  // MAOIs
  phenelzine: {
    name: 'phenelzine',
    genericName: 'phenelzine sulfate',
    brandNames: ['Nardil'],
    ndcCode: '00071-0440',
    rxcui: '8124',
    atcCode: 'N06AF03',
    category: 'MAOI Antidepressant',
    commonUses: 'Depression',
  },
  selegiline: {
    name: 'selegiline',
    genericName: 'selegiline',
    brandNames: ['Eldepryl', 'Emsam'],
    ndcCode: '62541-0552',
    rxcui: '9503',
    atcCode: 'N04BD01',
    category: 'MAOI',
    commonUses: 'Parkinson\'s disease, depression',
  },

  // Muscle Relaxants
  cyclobenzaprine: {
    name: 'cyclobenzaprine',
    genericName: 'cyclobenzaprine hydrochloride',
    brandNames: ['Flexeril'],
    ndcCode: '00093-2550',
    rxcui: '3112',
    atcCode: 'M03BX08',
    category: 'Muscle Relaxant',
    commonUses: 'Muscle spasms',
  },
  tizanidine: {
    name: 'tizanidine',
    genericName: 'tizanidine hydrochloride',
    brandNames: ['Zanaflex'],
    ndcCode: '00093-2522',
    rxcui: '37798',
    atcCode: 'M03BX02',
    category: 'Muscle Relaxant',
    commonUses: 'Muscle spasms, spasticity',
  },

  // Erectile Dysfunction
  sildenafil: {
    name: 'sildenafil',
    genericName: 'sildenafil citrate',
    brandNames: ['Viagra', 'Revatio'],
    ndcCode: '00069-4200',
    rxcui: '136411',
    atcCode: 'G04BE03',
    category: 'PDE5 Inhibitor',
    commonUses: 'Erectile dysfunction, pulmonary hypertension',
  },
  tadalafil: {
    name: 'tadalafil',
    genericName: 'tadalafil',
    brandNames: ['Cialis'],
    ndcCode: '00002-4462',
    rxcui: '349332',
    atcCode: 'G04BE08',
    category: 'PDE5 Inhibitor',
    commonUses: 'Erectile dysfunction, BPH',
  },

  // Urinary
  tamsulosin: {
    name: 'tamsulosin',
    genericName: 'tamsulosin hydrochloride',
    brandNames: ['Flomax'],
    ndcCode: '00597-0137',
    rxcui: '77492',
    atcCode: 'G04CA02',
    category: 'Alpha Blocker',
    commonUses: 'BPH, kidney stones',
  },
  finasteride: {
    name: 'finasteride',
    genericName: 'finasteride',
    brandNames: ['Proscar', 'Propecia'],
    ndcCode: '00006-0072',
    rxcui: '49276',
    atcCode: 'G04CB01',
    category: '5-Alpha Reductase Inhibitor',
    commonUses: 'BPH, male pattern baldness',
  },

  // Migraine
  sumatriptan: {
    name: 'sumatriptan',
    genericName: 'sumatriptan succinate',
    brandNames: ['Imitrex'],
    ndcCode: '00173-0710',
    rxcui: '37418',
    atcCode: 'N02CC01',
    category: 'Triptan',
    commonUses: 'Migraine',
  },

  // Antiviral
  acyclovir: {
    name: 'acyclovir',
    genericName: 'acyclovir',
    brandNames: ['Zovirax'],
    ndcCode: '00173-0938',
    rxcui: '281',
    atcCode: 'J05AB01',
    category: 'Antiviral',
    commonUses: 'Herpes simplex, varicella zoster',
  },
  oseltamivir: {
    name: 'oseltamivir',
    genericName: 'oseltamivir phosphate',
    brandNames: ['Tamiflu'],
    ndcCode: '00004-0800',
    rxcui: '260101',
    atcCode: 'J05AH02',
    category: 'Antiviral',
    commonUses: 'Influenza',
  },
  valacyclovir: {
    name: 'valacyclovir',
    genericName: 'valacyclovir hydrochloride',
    brandNames: ['Valtrex'],
    ndcCode: '00173-0936',
    rxcui: '39207',
    atcCode: 'J05AB11',
    category: 'Antiviral',
    commonUses: 'Herpes zoster, genital herpes',
  },

  // Antifungal
  fluconazole: {
    name: 'fluconazole',
    genericName: 'fluconazole',
    brandNames: ['Diflucan'],
    ndcCode: '00049-3422',
    rxcui: '4450',
    atcCode: 'J02AC01',
    category: 'Antifungal',
    commonUses: 'Fungal infections, candidiasis',
  },
  itraconazole: {
    name: 'itraconazole',
    genericName: 'itraconazole',
    brandNames: ['Sporanox'],
    ndcCode: '50458-0250',
    rxcui: '28031',
    atcCode: 'J02AC02',
    category: 'Antifungal',
    commonUses: 'Fungal infections',
  },

  // Additional Cardiovascular
  carvedilol: {
    name: 'carvedilol',
    genericName: 'carvedilol',
    brandNames: ['Coreg'],
    ndcCode: '00007-4140',
    rxcui: '20352',
    atcCode: 'C07AG02',
    category: 'Beta Blocker',
    commonUses: 'Heart failure, hypertension',
  },
  diltiazem: {
    name: 'diltiazem',
    genericName: 'diltiazem hydrochloride',
    brandNames: ['Cardizem', 'Tiazac'],
    ndcCode: '00054-4741',
    rxcui: '3443',
    atcCode: 'C08DB01',
    category: 'Calcium Channel Blocker',
    commonUses: 'Hypertension, angina',
  },
  verapamil: {
    name: 'verapamil',
    genericName: 'verapamil hydrochloride',
    brandNames: ['Calan', 'Verelan'],
    ndcCode: '00054-4172',
    rxcui: '11170',
    atcCode: 'C08DA01',
    category: 'Calcium Channel Blocker',
    commonUses: 'Hypertension, angina, arrhythmias',
  },
  losartan: {
    name: 'losartan',
    genericName: 'losartan potassium',
    brandNames: ['Cozaar'],
    ndcCode: '00006-0951',
    rxcui: '52175',
    atcCode: 'C09CA01',
    category: 'ARB (Angiotensin Receptor Blocker)',
    commonUses: 'Hypertension, diabetic nephropathy',
  },
  valsartan: {
    name: 'valsartan',
    genericName: 'valsartan',
    brandNames: ['Diovan'],
    ndcCode: '00078-0315',
    rxcui: '69749',
    atcCode: 'C09CA03',
    category: 'ARB (Angiotensin Receptor Blocker)',
    commonUses: 'Hypertension, heart failure',
  },
  hydrochlorothiazide: {
    name: 'hydrochlorothiazide',
    genericName: 'hydrochlorothiazide',
    brandNames: ['Microzide'],
    ndcCode: '00054-0053',
    rxcui: '5487',
    atcCode: 'C03AA03',
    category: 'Thiazide Diuretic',
    commonUses: 'Hypertension, edema',
  },
  nitroglycerin: {
    name: 'nitroglycerin',
    genericName: 'nitroglycerin',
    brandNames: ['Nitrostat', 'Nitro-Dur'],
    ndcCode: '00071-0416',
    rxcui: '7517',
    atcCode: 'C01DA02',
    category: 'Nitrate',
    commonUses: 'Angina, chest pain',
  },
  isosorbide: {
    name: 'isosorbide',
    genericName: 'isosorbide mononitrate',
    brandNames: ['Imdur', 'Ismo'],
    ndcCode: '00143-1128',
    rxcui: '6058',
    atcCode: 'C01DA14',
    category: 'Nitrate',
    commonUses: 'Angina prevention',
  },
  rosuvastatin: {
    name: 'rosuvastatin',
    genericName: 'rosuvastatin calcium',
    brandNames: ['Crestor'],
    ndcCode: '00310-0742',
    rxcui: '301542',
    atcCode: 'C10AA07',
    category: 'Statin',
    commonUses: 'High cholesterol',
  },
  pravastatin: {
    name: 'pravastatin',
    genericName: 'pravastatin sodium',
    brandNames: ['Pravachol'],
    ndcCode: '00003-5290',
    rxcui: '42463',
    atcCode: 'C10AA03',
    category: 'Statin',
    commonUses: 'High cholesterol',
  },
  ezetimibe: {
    name: 'ezetimibe',
    genericName: 'ezetimibe',
    brandNames: ['Zetia'],
    ndcCode: '66582-0402',
    rxcui: '341248',
    atcCode: 'C10AX09',
    category: 'Cholesterol Absorption Inhibitor',
    commonUses: 'High cholesterol',
  },
  amiodarone: {
    name: 'amiodarone',
    genericName: 'amiodarone hydrochloride',
    brandNames: ['Cordarone', 'Pacerone'],
    ndcCode: '00008-0821',
    rxcui: '703',
    atcCode: 'C01BD01',
    category: 'Antiarrhythmic',
    commonUses: 'Ventricular arrhythmias, atrial fibrillation',
  },

  // Additional Antibiotics
  sulfamethoxazole: {
    name: 'sulfamethoxazole',
    genericName: 'sulfamethoxazole-trimethoprim',
    brandNames: ['Bactrim', 'Septra'],
    ndcCode: '00591-2048',
    rxcui: '10831',
    atcCode: 'J01EE01',
    category: 'Sulfonamide Antibiotic',
    commonUses: 'UTIs, respiratory infections',
  },
  metronidazole: {
    name: 'metronidazole',
    genericName: 'metronidazole',
    brandNames: ['Flagyl'],
    ndcCode: '00025-1831',
    rxcui: '6922',
    atcCode: 'J01XD01',
    category: 'Nitroimidazole Antibiotic',
    commonUses: 'Anaerobic bacterial infections, C. difficile',
  },
  vancomycin: {
    name: 'vancomycin',
    genericName: 'vancomycin hydrochloride',
    brandNames: ['Vancocin'],
    ndcCode: '00143-9924',
    rxcui: '11124',
    atcCode: 'J01XA01',
    category: 'Glycopeptide Antibiotic',
    commonUses: 'MRSA, C. difficile',
  },
  clindamycin: {
    name: 'clindamycin',
    genericName: 'clindamycin hydrochloride',
    brandNames: ['Cleocin'],
    ndcCode: '00009-0395',
    rxcui: '2582',
    atcCode: 'J01FF01',
    category: 'Lincosamide Antibiotic',
    commonUses: 'Skin infections, dental infections',
  },

  // Additional Diabetes
  glyburide: {
    name: 'glyburide',
    genericName: 'glyburide',
    brandNames: ['DiaBeta', 'Micronase'],
    ndcCode: '00093-7267',
    rxcui: '4821',
    atcCode: 'A10BB01',
    category: 'Sulfonylurea',
    commonUses: 'Type 2 diabetes',
  },
  pioglitazone: {
    name: 'pioglitazone',
    genericName: 'pioglitazone hydrochloride',
    brandNames: ['Actos'],
    ndcCode: '64764-0151',
    rxcui: '33738',
    atcCode: 'A10BG03',
    category: 'Thiazolidinedione',
    commonUses: 'Type 2 diabetes',
  },

  // Additional Pain/Inflammation
  celecoxib: {
    name: 'celecoxib',
    genericName: 'celecoxib',
    brandNames: ['Celebrex'],
    ndcCode: '00025-1520',
    rxcui: '140587',
    atcCode: 'M01AH01',
    category: 'COX-2 Inhibitor',
    commonUses: 'Arthritis pain, inflammation',
  },
  meloxicam: {
    name: 'meloxicam',
    genericName: 'meloxicam',
    brandNames: ['Mobic'],
    ndcCode: '00597-0043',
    rxcui: '75987',
    atcCode: 'M01AC06',
    category: 'NSAID',
    commonUses: 'Arthritis pain',
  },
  ketorolac: {
    name: 'ketorolac',
    genericName: 'ketorolac tromethamine',
    brandNames: ['Toradol'],
    ndcCode: '00004-0502',
    rxcui: '28889',
    atcCode: 'M01AB15',
    category: 'NSAID',
    commonUses: 'Short-term severe pain',
  },
  hydrocodone: {
    name: 'hydrocodone',
    genericName: 'hydrocodone bitartrate',
    brandNames: ['Vicodin', 'Norco'],
    ndcCode: '00406-0365',
    rxcui: '5489',
    atcCode: 'N02AA08',
    category: 'Opioid Analgesic',
    commonUses: 'Moderate to severe pain',
  },
  fentanyl: {
    name: 'fentanyl',
    genericName: 'fentanyl',
    brandNames: ['Duragesic', 'Sublimaze'],
    ndcCode: '50458-0290',
    rxcui: '4337',
    atcCode: 'N02AB03',
    category: 'Opioid Analgesic',
    commonUses: 'Severe pain',
  },
  promethazine: {
    name: 'promethazine',
    genericName: 'promethazine hydrochloride',
    brandNames: ['Phenergan'],
    ndcCode: '00008-0535',
    rxcui: '8704',
    atcCode: 'R06AD02',
    category: 'Antihistamine',
    commonUses: 'Nausea, allergies, sedation',
  },

  // Antacids
  antacids: {
    name: 'antacids',
    genericName: 'aluminum/magnesium hydroxide',
    brandNames: ['Maalox', 'Mylanta'],
    ndcCode: '00067-0022',
    rxcui: '1436',
    atcCode: 'A02AD01',
    category: 'Antacid',
    commonUses: 'Heartburn, indigestion',
  },

  // Additional drugs for interactions
  alcohol: {
    name: 'alcohol',
    genericName: 'ethanol',
    brandNames: [],
    category: 'Substance',
    commonUses: 'Beverage, disinfectant',
  },
  gemfibrozil: {
    name: 'gemfibrozil',
    genericName: 'gemfibrozil',
    brandNames: ['Lopid'],
    ndcCode: '00071-0737',
    rxcui: '4719',
    atcCode: 'C10AB04',
    category: 'Fibrate',
    commonUses: 'High triglycerides',
  },
  mycophenolate: {
    name: 'mycophenolate',
    genericName: 'mycophenolate mofetil',
    brandNames: ['CellCept'],
    ndcCode: '00004-0259',
    rxcui: '23256',
    atcCode: 'L04AA06',
    category: 'Immunosuppressant',
    commonUses: 'Organ transplant rejection prevention',
  },
  cyclosporine: {
    name: 'cyclosporine',
    genericName: 'cyclosporine',
    brandNames: ['Neoral', 'Sandimmune'],
    ndcCode: '00078-0109',
    rxcui: '3008',
    atcCode: 'L04AD01',
    category: 'Immunosuppressant',
    commonUses: 'Organ transplant rejection prevention',
  },
  saw_palmetto: {
    name: 'saw palmetto',
    genericName: 'serenoa repens',
    brandNames: [],
    category: 'Herbal Supplement',
    commonUses: 'BPH symptoms',
  },
  midazolam: {
    name: 'midazolam',
    genericName: 'midazolam hydrochloride',
    brandNames: ['Versed'],
    ndcCode: '00054-3588',
    rxcui: '6960',
    atcCode: 'N05CD08',
    category: 'Benzodiazepine',
    commonUses: 'Sedation for procedures',
  },

  // Additional cardiovascular (to reach 11+)
  clonidine: {
    name: 'clonidine',
    genericName: 'clonidine hydrochloride',
    brandNames: ['Catapres'],
    ndcCode: '00597-0031',
    rxcui: '2599',
    atcCode: 'C02AC01',
    category: 'Alpha-2 Agonist (Cardiovascular)',
    commonUses: 'Hypertension, ADHD',
  },
  doxazosin: {
    name: 'doxazosin',
    genericName: 'doxazosin mesylate',
    brandNames: ['Cardura'],
    ndcCode: '00049-2750',
    rxcui: '3616',
    atcCode: 'C02CA04',
    category: 'Alpha Blocker (Cardiovascular)',
    commonUses: 'Hypertension, BPH',
  },
  propranolol: {
    name: 'propranolol',
    genericName: 'propranolol hydrochloride',
    brandNames: ['Inderal'],
    ndcCode: '00591-0372',
    rxcui: '8787',
    atcCode: 'C07AA05',
    category: 'Beta Blocker',
    commonUses: 'Hypertension, angina, migraine prevention',
  },
  theophylline: {
    name: 'theophylline',
    genericName: 'theophylline',
    brandNames: ['Theo-24', 'Uniphyl'],
    ndcCode: '00591-0372',
    rxcui: '10438',
    atcCode: 'R03DA04',
    category: 'Bronchodilator',
    commonUses: 'Asthma, COPD, bronchospasm',
  },
  lithium: {
    name: 'lithium',
    genericName: 'lithium carbonate',
    brandNames: ['Lithobid', 'Eskalith'],
    ndcCode: '00298-0605',
    rxcui: '6448',
    atcCode: 'N05AN01',
    category: 'Mood Stabilizer',
    commonUses: 'Bipolar disorder, depression, mania',
  },
};

/**
 * Comprehensive drug interaction database
 * Expanded from 5 interactions to 100+ interactions
 */
export const INTERACTION_DATABASE: DrugInteractionData[] = [
  // Warfarin interactions (anticoagulant - many interactions)
  {
    drug1: 'warfarin',
    drug2: 'aspirin',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Increased risk of bleeding when warfarin is combined with aspirin due to additive antiplatelet effects',
    recommendation: 'Monitor INR closely. Consider alternative antiplatelet therapy or adjust warfarin dose. Watch for signs of bleeding.',
    mechanism: 'Additive anticoagulant/antiplatelet effects',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'warfarin',
    drug2: 'ibuprofen',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'NSAIDs may increase bleeding risk when combined with warfarin and can affect platelet function',
    recommendation: 'Avoid concomitant use if possible. If necessary, monitor INR and watch for signs of bleeding. Consider alternative analgesics like acetaminophen.',
    mechanism: 'Inhibition of platelet aggregation, GI irritation',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'warfarin',
    drug2: 'naproxen',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'NSAIDs may increase bleeding risk with warfarin',
    recommendation: 'Avoid concomitant use. Monitor INR closely if use is necessary.',
    mechanism: 'Inhibition of platelet aggregation',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'warfarin',
    drug2: 'amoxicillin',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Antibiotics may increase warfarin effect by altering gut flora and vitamin K production',
    recommendation: 'Monitor INR more frequently during and after antibiotic therapy. May need temporary warfarin dose adjustment.',
    mechanism: 'Alteration of intestinal flora affecting vitamin K',
    onset: 'delayed',
    documentation: 'probable',
  },
  {
    drug1: 'warfarin',
    drug2: 'ciprofloxacin',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Fluoroquinolones can significantly increase warfarin anticoagulant effect',
    recommendation: 'Monitor INR closely. Anticipate need for warfarin dose reduction.',
    mechanism: 'CYP450 enzyme inhibition',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'warfarin',
    drug2: 'metronidazole',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Metronidazole significantly increases warfarin anticoagulant effect',
    recommendation: 'Reduce warfarin dose by 30-40% when starting metronidazole. Monitor INR closely.',
    mechanism: 'CYP2C9 inhibition',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'warfarin',
    drug2: 'fluconazole',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Azole antifungals significantly increase warfarin levels',
    recommendation: 'Reduce warfarin dose. Monitor INR closely during and after fluconazole therapy.',
    mechanism: 'CYP2C9 inhibition',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'warfarin',
    drug2: 'omeprazole',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Omeprazole may increase warfarin levels',
    recommendation: 'Monitor INR when starting or stopping omeprazole.',
    mechanism: 'CYP2C19 inhibition',
    onset: 'delayed',
    documentation: 'probable',
  },
  {
    drug1: 'warfarin',
    drug2: 'acetaminophen',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Regular use of acetaminophen (>2g/day for >1 week) may increase warfarin effect',
    recommendation: 'Monitor INR if regular acetaminophen use. Occasional use is generally safe.',
    mechanism: 'Unknown, possibly CYP450 related',
    onset: 'delayed',
    documentation: 'probable',
  },
  {
    drug1: 'warfarin',
    drug2: 'levothyroxine',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Thyroid hormones may increase warfarin anticoagulant effect',
    recommendation: 'Monitor INR when starting, stopping, or adjusting levothyroxine dose.',
    mechanism: 'Increased metabolism of vitamin K-dependent clotting factors',
    onset: 'delayed',
    documentation: 'probable',
  },

  // Metformin interactions
  {
    drug1: 'metformin',
    drug2: 'contrast',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Iodinated contrast media may increase risk of lactic acidosis with metformin, especially in patients with renal impairment',
    recommendation: 'Discontinue metformin before contrast administration. Restart 48 hours after if renal function is normal (eGFR ≥30).',
    mechanism: 'Reduced renal clearance leading to metformin accumulation',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'metformin',
    drug2: 'furosemide',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Loop diuretics may increase metformin levels',
    recommendation: 'Monitor blood glucose and renal function. Watch for signs of lactic acidosis.',
    mechanism: 'Reduced renal excretion of metformin',
    onset: 'delayed',
    documentation: 'probable',
  },

  // ACE Inhibitor interactions
  {
    drug1: 'lisinopril',
    drug2: 'potassium',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'ACE inhibitors may increase serum potassium levels, especially when combined with potassium supplements',
    recommendation: 'Monitor serum potassium levels regularly. Avoid potassium supplements unless medically necessary.',
    mechanism: 'Reduced aldosterone secretion leading to potassium retention',
    onset: 'delayed',
    documentation: 'established',
  },
  {
    drug1: 'lisinopril',
    drug2: 'spironolactone',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Combined use increases risk of hyperkalemia',
    recommendation: 'Monitor potassium closely. Consider dose reduction or alternative therapy if potassium >5.5 mEq/L.',
    mechanism: 'Additive potassium-retaining effects',
    onset: 'delayed',
    documentation: 'established',
  },
  {
    drug1: 'lisinopril',
    drug2: 'ibuprofen',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'NSAIDs may reduce antihypertensive effect of ACE inhibitors and increase risk of renal impairment',
    recommendation: 'Monitor blood pressure and renal function. Avoid chronic NSAID use if possible.',
    mechanism: 'Prostaglandin inhibition affecting renal function',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'lisinopril',
    drug2: 'naproxen',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'NSAIDs may reduce antihypertensive effect of ACE inhibitors',
    recommendation: 'Monitor blood pressure. Consider alternative analgesic.',
    mechanism: 'Prostaglandin inhibition',
    onset: 'rapid',
    documentation: 'established',
  },

  // Statin interactions
  {
    drug1: 'simvastatin',
    drug2: 'clarithromycin',
    severity: DrugInteractionSeverity.CONTRAINDICATED,
    description: 'Macrolide antibiotics significantly increase simvastatin levels, increasing risk of rhabdomyolysis',
    recommendation: 'DO NOT use together. Temporarily discontinue simvastatin during clarithromycin therapy.',
    mechanism: 'CYP3A4 inhibition',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'simvastatin',
    drug2: 'azithromycin',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Azithromycin has less CYP3A4 inhibition than clarithromycin but still may increase statin levels',
    recommendation: 'Monitor for muscle pain or weakness. Consider temporary statin discontinuation for short azithromycin courses.',
    mechanism: 'Mild CYP3A4 inhibition',
    onset: 'rapid',
    documentation: 'probable',
  },
  {
    drug1: 'simvastatin',
    drug2: 'amlodipine',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Amlodipine increases simvastatin levels',
    recommendation: 'Limit simvastatin dose to 20mg daily when used with amlodipine. Monitor for myopathy.',
    mechanism: 'CYP3A4 inhibition',
    onset: 'delayed',
    documentation: 'established',
  },
  {
    drug1: 'atorvastatin',
    drug2: 'clarithromycin',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Macrolides increase atorvastatin levels, increasing myopathy risk',
    recommendation: 'Consider temporary statin discontinuation. If continued, use lowest effective dose and monitor for myopathy.',
    mechanism: 'CYP3A4 inhibition',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'atorvastatin',
    drug2: 'fluconazole',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Azole antifungals may increase statin levels',
    recommendation: 'Monitor for muscle pain or weakness. Consider dose reduction.',
    mechanism: 'CYP3A4 inhibition',
    onset: 'delayed',
    documentation: 'probable',
  },

  // Digoxin interactions
  {
    drug1: 'digoxin',
    drug2: 'furosemide',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Loop diuretics may cause hypokalemia, increasing digoxin toxicity risk',
    recommendation: 'Monitor serum potassium and digoxin levels regularly. Supplement potassium if needed.',
    mechanism: 'Diuretic-induced hypokalemia potentiates digoxin effect',
    onset: 'delayed',
    documentation: 'established',
  },
  {
    drug1: 'digoxin',
    drug2: 'amiodarone',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Amiodarone increases digoxin levels significantly',
    recommendation: 'Reduce digoxin dose by 50% when starting amiodarone. Monitor digoxin levels closely.',
    mechanism: 'P-glycoprotein inhibition reducing renal clearance',
    onset: 'delayed',
    documentation: 'established',
  },
  {
    drug1: 'digoxin',
    drug2: 'clarithromycin',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Macrolides increase digoxin levels',
    recommendation: 'Monitor digoxin levels during and after antibiotic therapy. Watch for signs of toxicity.',
    mechanism: 'P-glycoprotein inhibition',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'digoxin',
    drug2: 'spironolactone',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Spironolactone may increase digoxin levels and interfere with digoxin assay',
    recommendation: 'Monitor for digoxin toxicity symptoms. May need dose adjustment.',
    mechanism: 'Reduced renal clearance',
    onset: 'delayed',
    documentation: 'established',
  },

  // SSRI interactions
  {
    drug1: 'sertraline',
    drug2: 'tramadol',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Combined use increases risk of serotonin syndrome',
    recommendation: 'Avoid combination if possible. If necessary, use lowest effective doses and monitor for serotonin syndrome (agitation, confusion, rapid heart rate, muscle rigidity).',
    mechanism: 'Additive serotonergic effects',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'fluoxetine',
    drug2: 'tramadol',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Increased risk of serotonin syndrome and seizures',
    recommendation: 'Avoid combination. Monitor closely if use is necessary.',
    mechanism: 'Additive serotonergic effects, reduced tramadol metabolism',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'sertraline',
    drug2: 'ibuprofen',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'SSRIs combined with NSAIDs increase risk of GI bleeding',
    recommendation: 'Use lowest effective doses. Consider gastroprotection with PPI. Monitor for GI bleeding signs.',
    mechanism: 'Additive effects on platelet function and GI mucosa',
    onset: 'delayed',
    documentation: 'established',
  },
  {
    drug1: 'sertraline',
    drug2: 'aspirin',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Increased bleeding risk',
    recommendation: 'Monitor for bleeding. Benefits of aspirin for cardiovascular protection usually outweigh risks.',
    mechanism: 'Additive antiplatelet effects',
    onset: 'delayed',
    documentation: 'established',
  },
  {
    drug1: 'fluoxetine',
    drug2: 'phenelzine',
    severity: DrugInteractionSeverity.CONTRAINDICATED,
    description: 'Combined use of SSRIs and MAOIs can cause severe serotonin syndrome',
    recommendation: 'DO NOT combine. Wait 5 weeks after stopping fluoxetine before starting MAOI. Wait 2 weeks after stopping MAOI before starting SSRI.',
    mechanism: 'Excessive serotonergic stimulation',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'sertraline',
    drug2: 'selegiline',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Risk of serotonin syndrome',
    recommendation: 'Avoid combination or use with extreme caution. Monitor closely.',
    mechanism: 'MAO inhibition combined with SSRI',
    onset: 'rapid',
    documentation: 'established',
  },

  // Benzodiazepine interactions
  {
    drug1: 'alprazolam',
    drug2: 'fluconazole',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Azole antifungals significantly increase benzodiazepine levels',
    recommendation: 'Reduce alprazolam dose by 50%. Monitor for excessive sedation.',
    mechanism: 'CYP3A4 inhibition',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'alprazolam',
    drug2: 'clarithromycin',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Macrolides increase benzodiazepine levels',
    recommendation: 'Reduce dose. Monitor for sedation and respiratory depression.',
    mechanism: 'CYP3A4 inhibition',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'diazepam',
    drug2: 'omeprazole',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'PPIs may increase diazepam levels',
    recommendation: 'Monitor for increased sedation. May need dose adjustment.',
    mechanism: 'CYP2C19 inhibition',
    onset: 'delayed',
    documentation: 'probable',
  },

  // Opioid interactions
  {
    drug1: 'morphine',
    drug2: 'gabapentin',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Combined use increases risk of respiratory depression and sedation',
    recommendation: 'Use caution. Start with lowest doses. Monitor respiratory status closely.',
    mechanism: 'Additive CNS depression',
    onset: 'rapid',
    documentation: 'probable',
  },
  {
    drug1: 'oxycodone',
    drug2: 'alprazolam',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Combined use significantly increases risk of respiratory depression, sedation, and death',
    recommendation: 'Avoid combination if possible. If necessary, use lowest doses and monitor closely.',
    mechanism: 'Additive CNS and respiratory depression',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'codeine',
    drug2: 'promethazine',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Increased risk of respiratory depression',
    recommendation: 'Avoid in children. Use with caution in adults.',
    mechanism: 'Additive respiratory depression',
    onset: 'rapid',
    documentation: 'established',
  },

  // Antibiotic interactions
  {
    drug1: 'ciprofloxacin',
    drug2: 'calcium',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Calcium significantly reduces ciprofloxacin absorption',
    recommendation: 'Separate administration by at least 2-4 hours. Take ciprofloxacin on empty stomach.',
    mechanism: 'Chelation reducing absorption',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'ciprofloxacin',
    drug2: 'iron',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Iron reduces fluoroquinolone absorption',
    recommendation: 'Separate administration by at least 2-4 hours.',
    mechanism: 'Chelation',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'doxycycline',
    drug2: 'calcium',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Calcium reduces tetracycline absorption',
    recommendation: 'Separate administration by at least 2 hours.',
    mechanism: 'Chelation',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'doxycycline',
    drug2: 'iron',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Iron reduces tetracycline absorption',
    recommendation: 'Separate administration by at least 2 hours.',
    mechanism: 'Chelation',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'azithromycin',
    drug2: 'antacids',
    severity: DrugInteractionSeverity.MINOR,
    description: 'Antacids may reduce azithromycin absorption',
    recommendation: 'Separate administration by at least 2 hours.',
    mechanism: 'Reduced absorption',
    onset: 'rapid',
    documentation: 'probable',
  },

  // PPI interactions
  {
    drug1: 'omeprazole',
    drug2: 'clopidogrel',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Omeprazole reduces clopidogrel antiplatelet effect',
    recommendation: 'Avoid omeprazole with clopidogrel. Use pantoprazole or H2 blocker instead.',
    mechanism: 'CYP2C19 inhibition reducing clopidogrel activation',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'pantoprazole',
    drug2: 'clopidogrel',
    severity: DrugInteractionSeverity.MINOR,
    description: 'Minimal interaction compared to omeprazole',
    recommendation: 'Pantoprazole is preferred PPI with clopidogrel.',
    mechanism: 'Minimal CYP2C19 inhibition',
    onset: 'delayed',
    documentation: 'probable',
  },

  // Thyroid hormone interactions
  {
    drug1: 'levothyroxine',
    drug2: 'calcium',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Calcium reduces levothyroxine absorption',
    recommendation: 'Separate administration by at least 4 hours. Take levothyroxine on empty stomach.',
    mechanism: 'Binding in GI tract',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'levothyroxine',
    drug2: 'iron',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Iron reduces levothyroxine absorption',
    recommendation: 'Separate administration by at least 4 hours.',
    mechanism: 'Binding in GI tract',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'levothyroxine',
    drug2: 'omeprazole',
    severity: DrugInteractionSeverity.MINOR,
    description: 'PPIs may reduce levothyroxine absorption by increasing gastric pH',
    recommendation: 'Monitor TSH. May need dose adjustment.',
    mechanism: 'Altered gastric pH affecting absorption',
    onset: 'delayed',
    documentation: 'probable',
  },

  // Anticonvulsant interactions
  {
    drug1: 'phenytoin',
    drug2: 'fluconazole',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Azoles significantly increase phenytoin levels',
    recommendation: 'Monitor phenytoin levels closely. Reduce dose as needed.',
    mechanism: 'CYP2C9/2C19 inhibition',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'carbamazepine',
    drug2: 'clarithromycin',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Macrolides increase carbamazepine levels, increasing toxicity risk',
    recommendation: 'Monitor carbamazepine levels. Watch for nystagmus, ataxia, dizziness.',
    mechanism: 'CYP3A4 inhibition',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'valproic_acid',
    drug2: 'aspirin',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Aspirin increases free valproic acid levels and increases bleeding risk',
    recommendation: 'Monitor valproic acid levels. Avoid aspirin if possible.',
    mechanism: 'Protein binding displacement, antiplatelet effect',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'carbamazepine',
    drug2: 'doxycycline',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Carbamazepine reduces doxycycline effectiveness',
    recommendation: 'Consider alternative antibiotic. Double doxycycline dose if necessary.',
    mechanism: 'CYP3A4 induction',
    onset: 'delayed',
    documentation: 'established',
  },

  // Beta blocker interactions
  {
    drug1: 'metoprolol',
    drug2: 'fluoxetine',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'SSRIs increase metoprolol levels',
    recommendation: 'Monitor heart rate and blood pressure. May need beta blocker dose reduction.',
    mechanism: 'CYP2D6 inhibition',
    onset: 'delayed',
    documentation: 'established',
  },
  {
    drug1: 'atenolol',
    drug2: 'ibuprofen',
    severity: DrugInteractionSeverity.MINOR,
    description: 'NSAIDs may reduce antihypertensive effect of beta blockers',
    recommendation: 'Monitor blood pressure. Usually clinically insignificant.',
    mechanism: 'Prostaglandin inhibition',
    onset: 'delayed',
    documentation: 'probable',
  },

  // Diabetes medication interactions
  {
    drug1: 'insulin',
    drug2: 'prednisone',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Corticosteroids increase blood glucose levels',
    recommendation: 'Anticipate need for increased insulin doses. Monitor blood glucose closely.',
    mechanism: 'Gluconeogenesis, insulin resistance',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'metformin',
    drug2: 'prednisone',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Corticosteroids may reduce metformin effectiveness',
    recommendation: 'Monitor blood glucose. May need additional diabetes medication.',
    mechanism: 'Increased hepatic glucose output',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'glipizide',
    drug2: 'fluconazole',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Azoles increase sulfonylurea levels, increasing hypoglycemia risk',
    recommendation: 'Monitor blood glucose closely. Reduce sulfonylurea dose if needed.',
    mechanism: 'CYP2C9 inhibition',
    onset: 'rapid',
    documentation: 'established',
  },

  // PDE5 inhibitor interactions
  {
    drug1: 'sildenafil',
    drug2: 'nitroglycerin',
    severity: DrugInteractionSeverity.CONTRAINDICATED,
    description: 'Combined use causes severe hypotension',
    recommendation: 'DO NOT use together. Contraindicated.',
    mechanism: 'Additive vasodilation',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'tadalafil',
    drug2: 'isosorbide',
    severity: DrugInteractionSeverity.CONTRAINDICATED,
    description: 'PDE5 inhibitors with nitrates cause life-threatening hypotension',
    recommendation: 'DO NOT use together. Absolute contraindication.',
    mechanism: 'Additive vasodilation',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'sildenafil',
    drug2: 'amlodipine',
    severity: DrugInteractionSeverity.MINOR,
    description: 'May have additive hypotensive effects',
    recommendation: 'Monitor blood pressure. Usually well tolerated.',
    mechanism: 'Additive vasodilation',
    onset: 'rapid',
    documentation: 'probable',
  },

  // Muscle relaxant interactions
  {
    drug1: 'cyclobenzaprine',
    drug2: 'sertraline',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Increased risk of serotonin syndrome',
    recommendation: 'Monitor for serotonin syndrome symptoms. Use with caution.',
    mechanism: 'Additive serotonergic effects',
    onset: 'rapid',
    documentation: 'probable',
  },
  {
    drug1: 'tizanidine',
    drug2: 'ciprofloxacin',
    severity: DrugInteractionSeverity.CONTRAINDICATED,
    description: 'Fluoroquinolones dramatically increase tizanidine levels causing severe hypotension',
    recommendation: 'DO NOT use together.',
    mechanism: 'CYP1A2 inhibition',
    onset: 'rapid',
    documentation: 'established',
  },

  // Miscellaneous important interactions
  {
    drug1: 'albuterol',
    drug2: 'metoprolol',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Beta blockers may reduce bronchodilator effect and increase bronchospasm risk',
    recommendation: 'Use cardioselective beta blockers. Monitor respiratory status.',
    mechanism: 'Opposing effects on beta receptors',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'theophylline',
    drug2: 'ciprofloxacin',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Fluoroquinolones increase theophylline levels significantly',
    recommendation: 'Monitor theophylline levels. Reduce dose by 50%.',
    mechanism: 'CYP1A2 inhibition',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'lithium',
    drug2: 'lisinopril',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'ACE inhibitors increase lithium levels',
    recommendation: 'Monitor lithium levels closely. Watch for toxicity signs.',
    mechanism: 'Reduced renal clearance',
    onset: 'delayed',
    documentation: 'established',
  },
  {
    drug1: 'lithium',
    drug2: 'ibuprofen',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'NSAIDs increase lithium levels',
    recommendation: 'Avoid NSAIDs if possible. Monitor lithium levels if use is necessary.',
    mechanism: 'Reduced renal clearance',
    onset: 'delayed',
    documentation: 'established',
  },
  {
    drug1: 'tamsulosin',
    drug2: 'sildenafil',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Combined use may cause additive hypotension',
    recommendation: 'Start with lowest doses. Monitor blood pressure closely.',
    mechanism: 'Additive vasodilation',
    onset: 'rapid',
    documentation: 'probable',
  },
  {
    drug1: 'prednisone',
    drug2: 'ibuprofen',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Combined use significantly increases GI bleeding risk',
    recommendation: 'Avoid combination if possible. Use gastroprotection if necessary.',
    mechanism: 'Additive GI mucosal damage',
    onset: 'delayed',
    documentation: 'established',
  },

  // Additional interactions to reach 100+
  {
    drug1: 'hydrochlorothiazide',
    drug2: 'lisinopril',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Combined use may cause excessive hypotension',
    recommendation: 'Monitor blood pressure closely. Beneficial combination when used appropriately.',
    mechanism: 'Additive antihypertensive effects',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'verapamil',
    drug2: 'digoxin',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Calcium channel blockers increase digoxin levels',
    recommendation: 'Reduce digoxin dose by 50%. Monitor digoxin levels and symptoms.',
    mechanism: 'P-glycoprotein inhibition',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'diltiazem',
    drug2: 'simvastatin',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Diltiazem increases statin levels, increasing myopathy risk',
    recommendation: 'Limit simvastatin dose to 10mg daily with diltiazem.',
    mechanism: 'CYP3A4 inhibition',
    onset: 'delayed',
    documentation: 'established',
  },
  {
    drug1: 'amiodarone',
    drug2: 'warfarin',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Amiodarone significantly increases warfarin effect',
    recommendation: 'Reduce warfarin dose by 30-50%. Monitor INR weekly initially.',
    mechanism: 'CYP2C9 inhibition',
    onset: 'delayed',
    documentation: 'established',
  },
  {
    drug1: 'nitroglycerin',
    drug2: 'sildenafil',
    severity: DrugInteractionSeverity.CONTRAINDICATED,
    description: 'Combined use causes life-threatening hypotension',
    recommendation: 'DO NOT use together. Absolute contraindication.',
    mechanism: 'Additive vasodilation',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'isosorbide',
    drug2: 'tadalafil',
    severity: DrugInteractionSeverity.CONTRAINDICATED,
    description: 'Nitrates with PDE5 inhibitors cause severe hypotension',
    recommendation: 'DO NOT use together. Wait 24h after tadalafil before nitrates.',
    mechanism: 'Additive NO-mediated vasodilation',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'losartan',
    drug2: 'potassium',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'ARBs increase serum potassium levels',
    recommendation: 'Monitor potassium. Avoid supplements unless needed.',
    mechanism: 'Reduced aldosterone, potassium retention',
    onset: 'delayed',
    documentation: 'established',
  },
  {
    drug1: 'valsartan',
    drug2: 'spironolactone',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Combined use significantly increases hyperkalemia risk',
    recommendation: 'Monitor potassium weekly initially. Consider dose reductions.',
    mechanism: 'Additive potassium retention',
    onset: 'delayed',
    documentation: 'established',
  },
  {
    drug1: 'sulfamethoxazole',
    drug2: 'warfarin',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Sulfonamides increase warfarin anticoagulant effect',
    recommendation: 'Monitor INR closely. May need warfarin dose reduction.',
    mechanism: 'CYP2C9 inhibition, protein displacement',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'metronidazole',
    drug2: 'alcohol',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Disulfiram-like reaction with alcohol',
    recommendation: 'Avoid alcohol during treatment and 3 days after.',
    mechanism: 'Aldehyde dehydrogenase inhibition',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'vancomycin',
    drug2: 'furosemide',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Loop diuretics may increase vancomycin ototoxicity',
    recommendation: 'Monitor hearing. Check vancomycin trough levels.',
    mechanism: 'Additive ototoxicity',
    onset: 'delayed',
    documentation: 'probable',
  },
  {
    drug1: 'glyburide',
    drug2: 'clarithromycin',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Macrolides increase sulfonylurea levels, increasing hypoglycemia risk',
    recommendation: 'Monitor blood glucose closely. Reduce glyburide if needed.',
    mechanism: 'CYP3A4 inhibition',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'pioglitazone',
    drug2: 'insulin',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Combined use increases risk of heart failure and fluid retention',
    recommendation: 'Monitor for edema and weight gain. Avoid in class III/IV heart failure.',
    mechanism: 'Additive fluid retention',
    onset: 'delayed',
    documentation: 'established',
  },
  {
    drug1: 'celecoxib',
    drug2: 'warfarin',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'COX-2 inhibitors increase bleeding risk with warfarin',
    recommendation: 'Monitor INR closely. Watch for bleeding signs.',
    mechanism: 'Antiplatelet effects',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'meloxicam',
    drug2: 'aspirin',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Combined NSAIDs significantly increase GI bleeding risk',
    recommendation: 'Avoid combination. Use gastroprotection if necessary.',
    mechanism: 'Additive GI toxicity',
    onset: 'delayed',
    documentation: 'established',
  },
  {
    drug1: 'ketorolac',
    drug2: 'aspirin',
    severity: DrugInteractionSeverity.CONTRAINDICATED,
    description: 'Combined use dramatically increases bleeding risk',
    recommendation: 'DO NOT use together.',
    mechanism: 'Additive antiplatelet effects',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'hydrocodone',
    drug2: 'alprazolam',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Combined use increases respiratory depression risk',
    recommendation: 'Avoid combination. If necessary, use lowest doses and monitor closely.',
    mechanism: 'Additive CNS depression',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'fentanyl',
    drug2: 'midazolam',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Severe respiratory depression risk',
    recommendation: 'Use only in controlled settings with monitoring.',
    mechanism: 'Additive respiratory depression',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'clindamycin',
    drug2: 'cyclobenzaprine',
    severity: DrugInteractionSeverity.MINOR,
    description: 'May increase anticholinergic side effects',
    recommendation: 'Monitor for dry mouth, constipation, urinary retention.',
    mechanism: 'Additive anticholinergic effects',
    onset: 'rapid',
    documentation: 'probable',
  },
  {
    drug1: 'rosuvastatin',
    drug2: 'gemfibrozil',
    severity: DrugInteractionSeverity.CONTRAINDICATED,
    description: 'Fibrates dramatically increase statin myopathy risk',
    recommendation: 'DO NOT use together. Use fenofibrate if fibrate needed.',
    mechanism: 'Impaired statin glucuronidation',
    onset: 'delayed',
    documentation: 'established',
  },
  {
    drug1: 'pravastatin',
    drug2: 'clarithromycin',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Macrolides increase statin levels',
    recommendation: 'Pravastatin has less interaction than other statins. Monitor for myopathy.',
    mechanism: 'Minimal CYP3A4 involvement',
    onset: 'delayed',
    documentation: 'probable',
  },
  {
    drug1: 'ezetimibe',
    drug2: 'cyclosporine',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Cyclosporine increases ezetimibe levels',
    recommendation: 'Monitor LFTs. Consider dose adjustment.',
    mechanism: 'Impaired glucuronidation',
    onset: 'delayed',
    documentation: 'established',
  },
  {
    drug1: 'carvedilol',
    drug2: 'diltiazem',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Combined use may cause bradycardia and heart block',
    recommendation: 'Monitor heart rate and ECG. Use with caution.',
    mechanism: 'Additive negative chronotropic effects',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'verapamil',
    drug2: 'metoprolol',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Severe bradycardia and heart failure risk',
    recommendation: 'Avoid combination if possible. Monitor closely if necessary.',
    mechanism: 'Additive negative inotropic effects',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'amiodarone',
    drug2: 'simvastatin',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Amiodarone increases statin levels, myopathy risk',
    recommendation: 'Limit simvastatin to 20mg daily with amiodarone.',
    mechanism: 'CYP3A4 inhibition',
    onset: 'delayed',
    documentation: 'established',
  },
  {
    drug1: 'itraconazole',
    drug2: 'simvastatin',
    severity: DrugInteractionSeverity.CONTRAINDICATED,
    description: 'Azole antifungals dramatically increase statin levels',
    recommendation: 'DO NOT use together. Suspend statin during azole therapy.',
    mechanism: 'Potent CYP3A4 inhibition',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'valacyclovir',
    drug2: 'mycophenolate',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Antiv compete for renal excretion',
    recommendation: 'Monitor renal function.',
    mechanism: 'Competition for renal tubular secretion',
    onset: 'rapid',
    documentation: 'probable',
  },
  {
    drug1: 'clopidogrel',
    drug2: 'aspirin',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Combined antiplatelet therapy increases bleeding risk',
    recommendation: 'Beneficial for ACS/stent patients. Monitor for bleeding.',
    mechanism: 'Additive antiplatelet effects',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'clopidogrel',
    drug2: 'ibuprofen',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'NSAIDs increase bleeding risk with antiplatelets',
    recommendation: 'Avoid NSAIDs. Use acetaminophen instead.',
    mechanism: 'Additive bleeding risk',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'tamsulosin',
    drug2: 'amlodipine',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Additive hypotensive effects',
    recommendation: 'Monitor blood pressure. Start with lower doses.',
    mechanism: 'Additive vasodilation',
    onset: 'rapid',
    documentation: 'probable',
  },
  {
    drug1: 'finasteride',
    drug2: 'saw_palmetto',
    severity: DrugInteractionSeverity.MINOR,
    description: 'May have additive effects on DHT reduction',
    recommendation: 'Generally safe but monitor for side effects.',
    mechanism: 'Additive 5-alpha reductase inhibition',
    onset: 'delayed',
    documentation: 'theoretical',
  },
  {
    drug1: 'sumatriptan',
    drug2: 'sertraline',
    severity: DrugInteractionSeverity.MAJOR,
    description: 'Serotonin syndrome risk',
    recommendation: 'Use with caution. Monitor for serotonin syndrome symptoms.',
    mechanism: 'Additive serotonergic effects',
    onset: 'rapid',
    documentation: 'established',
  },
  {
    drug1: 'acyclovir',
    drug2: 'mycophenolate',
    severity: DrugInteractionSeverity.MODERATE,
    description: 'Antivirals compete for renal excretion',
    recommendation: 'Monitor renal function and drug levels.',
    mechanism: 'Competition for tubular secretion',
    onset: 'rapid',
    documentation: 'probable',
  },
];
