apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metapharm

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - ingress.yaml
  - services/api-gateway.yaml
  - services/auth-service.yaml
  - services/prescription-service.yaml
  - services/postgres.yaml
  - services/redis.yaml

commonLabels:
  platform: metapharm
  managed-by: kustomize
