import * as promClient from 'prom-client';
export interface MetricValue {
    value: number;
    timestamp?: number;
}
export declare const httpRequestsTotal: promClient.Counter<"path" | "method" | "status_code">;
export declare const httpRequestDurationMs: promClient.Histogram<"path" | "method" | "status_code">;
export declare const httpResponseStatus: promClient.Counter<"status_code">;
export declare const slowRequests: promClient.Counter<"path" | "method">;
export declare const httpErrors: promClient.Counter<"path" | "method" | "status_code">;
export declare const activeRequests: promClient.Gauge<"path" | "method">;
export declare const cacheHits: promClient.Counter<"cache_name">;
export declare const cacheMisses: promClient.Counter<"cache_name">;
export declare const cacheSize: promClient.Gauge<"cache_name">;
export declare const dbQueries: promClient.Counter<"table" | "operation">;
export declare const dbQueryDurationMs: promClient.Histogram<"table" | "operation">;
export declare const dbErrors: promClient.Counter<"table" | "operation">;
export declare const dbConnectionPoolSize: promClient.Gauge<string>;
export declare const dbActiveConnections: promClient.Gauge<string>;
export declare const loginAttempts: promClient.Counter<"result">;
export declare const tokenValidations: promClient.Counter<"result">;
export declare const prescriptionsCreated: promClient.Counter<"pharmacy_id">;
export declare const ordersPlaced: promClient.Counter<"status">;
export declare const activeUsers: promClient.Gauge<string>;
export declare function recordRequestDuration(method: string, path: string, duration: number, statusCode: number): void;
export declare function recordSlowRequest(method: string, path: string, duration: number): void;
export declare function recordRequestStart(method: string, path: string): void;
export declare function recordRequestEnd(method: string, path: string): void;
export declare function recordCacheHit(cacheName: string): void;
export declare function recordCacheMiss(cacheName: string): void;
export declare function updateCacheSize(cacheName: string, sizeBytes: number): void;
export declare function recordDatabaseQuery(operation: string, table: string, duration: number): void;
export declare function recordDatabaseError(operation: string, table: string): void;
export declare function updateConnectionPoolStatus(total: number, active: number): void;
export declare function recordLoginAttempt(success: boolean): void;
export declare function recordTokenValidation(result: 'valid' | 'expired' | 'invalid'): void;
export declare function recordPrescriptionCreated(pharmacyId: string): void;
export declare function recordOrderPlaced(status: string): void;
export declare function updateActiveUsers(count: number): void;
export declare function getMetrics(): Promise<string>;
export declare function getMetricsAsJson(): Promise<any>;
export declare function clearMetrics(): void;
declare const _default: {
    getMetrics: typeof getMetrics;
    getMetricsAsJson: typeof getMetricsAsJson;
    recordRequestDuration: typeof recordRequestDuration;
    recordSlowRequest: typeof recordSlowRequest;
    recordCacheHit: typeof recordCacheHit;
    recordCacheMiss: typeof recordCacheMiss;
    updateCacheSize: typeof updateCacheSize;
    recordDatabaseQuery: typeof recordDatabaseQuery;
    recordDatabaseError: typeof recordDatabaseError;
    updateConnectionPoolStatus: typeof updateConnectionPoolStatus;
    recordLoginAttempt: typeof recordLoginAttempt;
    recordTokenValidation: typeof recordTokenValidation;
    recordPrescriptionCreated: typeof recordPrescriptionCreated;
    recordOrderPlaced: typeof recordOrderPlaced;
    updateActiveUsers: typeof updateActiveUsers;
};
export default _default;
//# sourceMappingURL=metrics.d.ts.map