apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
  labels:
    app: api-gateway
spec:
  type: ClusterIP  # Changed to ClusterIP, Ingress will handle external access
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  sessionAffinity: None
