apiVersion: v1
kind: Service
metadata:
  name: postgres-primary-svc
  namespace: metapharm
  labels:
    app: postgres-primary
    service: 'true'
  annotations:
    service.kubernetes.io/topology-aware-hints: auto
spec:
  selector:
    app: postgres-primary
  ports:
  - name: http
    protocol: TCP
    port: 5432
    targetPort: http
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
