apiVersion: v1
kind: Service
metadata:
  name: vip-service-svc
  namespace: metapharm
  labels:
    app: vip-service
    service: 'true'
  annotations:
    service.kubernetes.io/topology-aware-hints: auto
spec:
  selector:
    app: vip-service
  ports:
  - name: http
    protocol: TCP
    port: 3028
    targetPort: http
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
