import { defineConfig, devices } from '@playwright/test';

/**
 * Playwright Configuration for MetaPharm Connect Web Application
 *
 * This configuration sets up end-to-end testing for the pharmacist web app
 * with headless mode enabled for CI/CD compatibility.
 *
 * @see https://playwright.dev/docs/test-configuration
 */
export default defineConfig({
  // Test directory
  testDir: './e2e',

  // Maximum time one test can run
  timeout: 30 * 1000,

  // Expect timeout for assertions
  expect: {
    timeout: 5000,
  },

  // Run tests in files in parallel
  fullyParallel: true,

  // Fail the build on CI if you accidentally left test.only in the source code
  forbidOnly: !!process.env.CI,

  // Retry on CI only
  retries: process.env.CI ? 2 : 0,

  // Opt out of parallel tests on CI
  workers: process.env.CI ? 1 : undefined,

  // Reporter to use
  reporter: [
    ['html', { outputFolder: 'playwright-report' }],
    ['json', { outputFile: 'playwright-report/results.json' }],
    ['junit', { outputFile: 'playwright-report/junit.xml' }],
    ['list'], // Console output
  ],

  // Shared settings for all projects
  use: {
    // Base URL for navigation
    baseURL: process.env.PLAYWRIGHT_BASE_URL || 'http://localhost:5173',

    // Collect trace when retrying the failed test
    trace: 'on-first-retry',

    // Screenshot on failure
    screenshot: 'only-on-failure',

    // Video on failure
    video: 'retain-on-failure',

    // Default timeout for actions
    actionTimeout: 10000,

    // Default timeout for navigation
    navigationTimeout: 30000,

    // Extra HTTP headers
    extraHTTPHeaders: {
      'Accept-Language': 'fr-CH, fr;q=0.9, en;q=0.8',
    },
  },

  // Configure projects for different browsers
  projects: [
    // Role-specific projects with pre-authenticated states
    // These are generated by global-setup.ts and stored in .auth/{role}.json
    {
      name: 'pharmacist',
      use: {
        ...devices['Desktop Chrome'],
        headless: true,
        storageState: '.auth/pharmacist.json',
      },
    },

    {
      name: 'nurse',
      testMatch: '**/nurse*.spec.ts',
      use: {
        ...devices['Desktop Chrome'],
        headless: true,
        storageState: '.auth/nurse.json',
      },
    },

    {
      name: 'patient',
      use: {
        ...devices['Desktop Chrome'],
        headless: true,
        storageState: '.auth/patient.json',
      },
    },

    {
      name: 'doctor',
      use: {
        ...devices['Desktop Chrome'],
        headless: true,
        storageState: '.auth/doctor.json',
      },
    },

    {
      name: 'delivery',
      use: {
        ...devices['Desktop Chrome'],
        headless: true,
        storageState: '.auth/delivery.json',
      },
    },

    // Generic browser projects for unauthenticated tests
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        // Force headless mode
        headless: true,
      },
    },

    {
      name: 'firefox',
      use: {
        ...devices['Desktop Firefox'],
        // Force headless mode
        headless: true,
      },
    },

    {
      name: 'webkit',
      use: {
        ...devices['Desktop Safari'],
        // Force headless mode
        headless: true,
      },
    },

    // Mobile viewports for responsive testing
    {
      name: 'mobile-chrome',
      use: {
        ...devices['Pixel 5'],
        // Force headless mode
        headless: true,
      },
    },

    {
      name: 'mobile-safari',
      use: {
        ...devices['iPhone 12'],
        // Force headless mode
        headless: true,
      },
    },
  ],

  // Web server configuration - start dev server before tests
  webServer: {
    command: 'npm run dev',
    url: 'http://localhost:5173',
    // Always reuse existing server - in CI we start it explicitly for better error visibility
    reuseExistingServer: true,
    timeout: 120 * 1000, // 2 minutes to start
    stdout: 'pipe', // Show output for debugging
    stderr: 'pipe',
  },

  // Global setup and teardown
  globalSetup: './e2e/config/global-setup.ts',
  globalTeardown: './e2e/config/global-teardown.ts',
});
